//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.23 at 08:22:54 AM BOT 
//


package com.test.cv.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CVType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CVType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="personalia" type="{http://www.example.org/cv}PersonaliaType"/>
 *         &lt;element name="items" type="{http://www.example.org/cv}ItemsType" minOccurs="0"/>
 *         &lt;element name="skillategories" type="{http://www.example.org/cv}SkillCategoriesType" minOccurs="0"/>
 *         &lt;element name="skills" type="{http://www.example.org/cv}SkillsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CVType", propOrder = {
    "personalia",
    "items",
    "skillategories",
    "skills"
})
public class CVType {

    @XmlElement(required = true)
    protected PersonaliaType personalia;
    protected ItemsType items;
    protected SkillCategoriesType skillategories;
    protected SkillsType skills;

    /**
     * Gets the value of the personalia property.
     * 
     * @return
     *     possible object is
     *     {@link PersonaliaType }
     *     
     */
    public PersonaliaType getPersonalia() {
        return personalia;
    }

    /**
     * Sets the value of the personalia property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonaliaType }
     *     
     */
    public void setPersonalia(PersonaliaType value) {
        this.personalia = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link ItemsType }
     *     
     */
    public ItemsType getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemsType }
     *     
     */
    public void setItems(ItemsType value) {
        this.items = value;
    }

    /**
     * Gets the value of the skillategories property.
     * 
     * @return
     *     possible object is
     *     {@link SkillCategoriesType }
     *     
     */
    public SkillCategoriesType getSkillategories() {
        return skillategories;
    }

    /**
     * Sets the value of the skillategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkillCategoriesType }
     *     
     */
    public void setSkillategories(SkillCategoriesType value) {
        this.skillategories = value;
    }

    /**
     * Gets the value of the skills property.
     * 
     * @return
     *     possible object is
     *     {@link SkillsType }
     *     
     */
    public SkillsType getSkills() {
        return skills;
    }

    /**
     * Sets the value of the skills property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkillsType }
     *     
     */
    public void setSkills(SkillsType value) {
        this.skills = value;
    }

}
