package com.test.salesportal.common;

public class EnvVariables {
	
	public static final String SALESPORTAL_APPROVAL_NOTIFICATION_PHONENUMBER = "SALESPORTAL_APPROVAL_NOTIFICATION_PHONENUMBER";
	public static final String SALESPORTAL_JPA_USERNAME = "SALESPORTAL_JPA_USERNAME";
	public static final String SALESPORTAL_JPA_PASSWORD = "SALESPORTAL_JPA_PASSWORD";

	public static final String SALESPORTAL_LOCALHOST_TEST = "SALESPORTAL_LOCALHOST_TEST";
}

