//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.04 at 07:10:59 PM CLST 
//


package com.test.salesportal.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.test.cv.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NewElement_QNAME = new QName("http://www.example.org/cv", "NewElement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.test.cv.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EducationType }
     * 
     */
    public EducationType createEducationType() {
        return new EducationType();
    }

    /**
     * Create an instance of {@link TextsType }
     * 
     */
    public TextsType createTextsType() {
        return new TextsType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link SkillRefsType }
     * 
     */
    public SkillRefsType createSkillRefsType() {
        return new SkillRefsType();
    }

    /**
     * Create an instance of {@link SelfEmployedType }
     * 
     */
    public SelfEmployedType createSelfEmployedType() {
        return new SelfEmployedType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link CategoryType }
     * 
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link SkillsType }
     * 
     */
    public SkillsType createSkillsType() {
        return new SkillsType();
    }

    /**
     * Create an instance of {@link LinksType }
     * 
     */
    public LinksType createLinksType() {
        return new LinksType();
    }

    /**
     * Create an instance of {@link CustomType }
     * 
     */
    public CustomType createCustomType() {
        return new CustomType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link ItemsType }
     * 
     */
    public ItemsType createItemsType() {
        return new ItemsType();
    }

    /**
     * Create an instance of {@link DescribedItemType }
     * 
     */
    public DescribedItemType createDescribedItemType() {
        return new DescribedItemType();
    }

    /**
     * Create an instance of {@link PersonaliaType }
     * 
     */
    public PersonaliaType createPersonaliaType() {
        return new PersonaliaType();
    }

    /**
     * Create an instance of {@link WorkType }
     * 
     */
    public WorkType createWorkType() {
        return new WorkType();
    }

    /**
     * Create an instance of {@link ExitReasonType }
     * 
     */
    public ExitReasonType createExitReasonType() {
        return new ExitReasonType();
    }

    /**
     * Create an instance of {@link SkillType }
     * 
     */
    public SkillType createSkillType() {
        return new SkillType();
    }

    /**
     * Create an instance of {@link SkillCategoriesType }
     * 
     */
    public SkillCategoriesType createSkillCategoriesType() {
        return new SkillCategoriesType();
    }

    /**
     * Create an instance of {@link SkillsAquiringItemType }
     * 
     */
    public SkillsAquiringItemType createSkillsAquiringItemType() {
        return new SkillsAquiringItemType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link SummaryType }
     * 
     */
    public SummaryType createSummaryType() {
        return new SummaryType();
    }

    /**
     * Create an instance of {@link PositionType }
     * 
     */
    public PositionType createPositionType() {
        return new PositionType();
    }

    /**
     * Create an instance of {@link KeySkillType }
     * 
     */
    public KeySkillType createKeySkillType() {
        return new KeySkillType();
    }

    /**
     * Create an instance of {@link JobType }
     * 
     */
    public JobType createJobType() {
        return new JobType();
    }

    /**
     * Create an instance of {@link CVType }
     * 
     */
    public CVType createCVType() {
        return new CVType();
    }

    /**
     * Create an instance of {@link SkillRefType }
     * 
     */
    public SkillRefType createSkillRefType() {
        return new SkillRefType();
    }

    /**
     * Create an instance of {@link ProjectType }
     * 
     */
    public ProjectType createProjectType() {
        return new ProjectType();
    }

    /**
     * Create an instance of {@link KeySkillsType }
     * 
     */
    public KeySkillsType createKeySkillsType() {
        return new KeySkillsType();
    }

    /**
     * Create an instance of {@link CategoriesType }
     * 
     */
    public CategoriesType createCategoriesType() {
        return new CategoriesType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link SkillCategoryType }
     * 
     */
    public SkillCategoryType createSkillCategoryType() {
        return new SkillCategoryType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/cv", name = "NewElement")
    public JAXBElement<String> createNewElement(String value) {
        return new JAXBElement<String>(_NewElement_QNAME, String.class, null, value);
    }

}
