//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.04 at 07:10:59 PM CLST 
//


package com.test.salesportal.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SkillsAquiringItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkillsAquiringItemType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/cv}DescribedItemType">
 *       &lt;sequence>
 *         &lt;element name="skills" type="{http://www.example.org/cv}SkillRefsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkillsAquiringItemType", propOrder = {
    "skills"
})
@XmlSeeAlso({
    WorkType.class,
    ProjectType.class
})
public class SkillsAquiringItemType
    extends DescribedItemType
{

    protected SkillRefsType skills;

    /**
     * Gets the value of the skills property.
     * 
     * @return
     *     possible object is
     *     {@link SkillRefsType }
     *     
     */
    public SkillRefsType getSkills() {
        return skills;
    }

    /**
     * Sets the value of the skills property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkillRefsType }
     *     
     */
    public void setSkills(SkillRefsType value) {
        this.skills = value;
    }

}
